import type { SQL } from "drizzle-orm";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { useDb, schema } from "~~/server/utils/db";
import { requireRole } from "~~/server/utils/requireRole";
import { rateLimitByUser } from "~~/server/utils/rateLimit";
import { now } from "~~/server/utils/sqlTime";
import { isValidNtfyTopic, normalizeNtfyTopic } from "~~/server/utils/notify";

// `topic` omitted leaves whatever is stored alone, so the checkbox can be
// toggled without re-sending it. An empty string is the explicit "forget my
// topic" case, which the form uses when clearing the destination.
const Body = z.object({
  enabled: z.boolean(),
  topic: z.string().max(200).optional(),
});

export default defineEventHandler(async (event) => {
  const user = requireRole(event, "admin");
  await rateLimitByUser(event, "notify-settings", { max: 20, windowSec: 3600 });

  const body = await readValidatedBody(event, Body.parse);
  const db = useDb(event);

  const stored = await db
    .select({
      ntfyTopic: schema.users.ntfyTopic,
      adminNotifyAt: schema.users.adminNotifyAt,
    })
    .from(schema.users)
    .where(eq(schema.users.id, user.id))
    .get();

  // `adminNotifyAt` is set from `now()`, which is a SQL fragment rather than a
  // string: the timestamp is generated by the database, not by whichever edge
  // node happened to serve the request.
  const patch: {
    ntfyTopic?: string | null;
    adminNotifyAt?: string | SQL | null;
  } = {};

  if (body.topic !== undefined) {
    const topic = normalizeNtfyTopic(body.topic);
    if (topic.length === 0) {
      patch.ntfyTopic = null;
    } else if (!isValidNtfyTopic(topic)) {
      throw createError({
        statusCode: 422,
        statusMessage:
          "Topic can only use letters, numbers, dashes and underscores.",
      });
    } else {
      patch.ntfyTopic = topic;
    }
  }

  // Turning notifications on without anywhere to send them would leave the
  // checkbox claiming something the server cannot do, so it is refused rather
  // than silently stored. Checked against the write in flight, not just what
  // is already in the row, so setting a topic and ticking the box in one
  // submit works.
  if (body.enabled) {
    const effectiveTopic =
      patch.ntfyTopic !== undefined ? patch.ntfyTopic : stored?.ntfyTopic;
    if (!effectiveTopic) {
      throw createError({
        statusCode: 422,
        statusMessage: "Set an ntfy topic before turning notifications on.",
      });
    }
    // Only stamped when moving from off to on, so the column keeps saying when
    // this admin opted in rather than when they last touched the form.
    if (!stored?.adminNotifyAt) patch.adminNotifyAt = now();
  } else {
    patch.adminNotifyAt = null;
  }

  await db.update(schema.users).set(patch).where(eq(schema.users.id, user.id));

  return { ok: true, enabled: body.enabled };
});
