import type { SQL } from "drizzle-orm";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { useDb, schema } from "~~/server/utils/db";
import { requireRole } from "~~/server/utils/requireRole";
import { rateLimitByUser } from "~~/server/utils/rateLimit";
import { now } from "~~/server/utils/sqlTime";

// Only the opt-in. The destination is set by linking a Telegram chat through
// the bot, which proves the chat is the admin's, and never by typing one in.
const Body = z.object({
  enabled: z.boolean(),
});

export default defineEventHandler(async (event) => {
  const user = requireRole(event, "admin");
  await rateLimitByUser(event, "notify-settings", { max: 20, windowSec: 3600 });

  const body = await readValidatedBody(event, Body.parse);
  const db = useDb(event);

  const stored = await db
    .select({
      telegramChatId: schema.users.telegramChatId,
      adminNotifyAt: schema.users.adminNotifyAt,
    })
    .from(schema.users)
    .where(eq(schema.users.id, user.id))
    .get();

  // `adminNotifyAt` is set from `now()`, which is a SQL fragment rather than a
  // string: the timestamp is generated by the database, not by whichever edge
  // node happened to serve the request.
  let adminNotifyAt: string | SQL | null | undefined;

  if (body.enabled) {
    // Turning notifications on without anywhere to send them would leave the
    // checkbox claiming something the server cannot do, so it is refused
    // rather than silently stored.
    if (!stored?.telegramChatId) {
      throw createError({
        statusCode: 422,
        statusMessage: "Connect Telegram before turning notifications on.",
      });
    }
    // Only stamped when moving from off to on, so the column keeps saying when
    // this admin opted in rather than when they last touched the form.
    if (!stored.adminNotifyAt) adminNotifyAt = now();
  } else {
    adminNotifyAt = null;
  }

  if (adminNotifyAt !== undefined) {
    await db
      .update(schema.users)
      .set({ adminNotifyAt })
      .where(eq(schema.users.id, user.id));
  }

  return { ok: true, enabled: body.enabled };
});
