import { sql } from "drizzle-orm";

/**
 * SQLite's current UTC time, as a fragment for a Drizzle `set()` or `values()`.
 *
 * Every timestamp column in the schema defaults to `datetime('now')`, and every
 * handler that updates one has to restate that expression. Naming it once keeps
 * the format identical everywhere, which matters because
 * `shared/utils/sqliteTime.ts` parses these strings back on the assumption that
 * they are `YYYY-MM-DD HH:MM:SS` in UTC.
 *
 * Generated by the database rather than the worker, so the value does not
 * depend on an edge node's clock.
 */
export function now() {
  return sql`(datetime('now'))`;
}

/**
 * A UTC timestamp a whole number of days in the future, for setting a mute
 * expiry.
 *
 * The offset is bound as a parameter rather than interpolated. `days` reaches
 * this from a request body, and although the Zod schema constrains it to a
 * positive integer, building SQL by string concatenation from request data is
 * not a habit worth keeping even where it currently happens to be safe.
 */
export function daysFromNow(days: number) {
  return sql`datetime('now', ${`+${days} days`})`;
}
